### ISSUE TITLE
Several strings are not localized in onboarding and autofill screens

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-lockwise/lockwise-ios#1009]
Multiple strings are either hardcoded,  haven’t been exposed to the xliff file, or are not used. Adding screenshots below

- [x] “Deselect iCloud keychain” → Not exposed to Pontoon (#1032)
- [x] “Firefox Lockbox will use Face ID to sign you in to the app” → Not exposed to Pontoon (#992)
- [ ] “Sync between devices with secure 256-bits encryption” → Exposed, but not used
- The headline in the instruction screen could use a line break, too (moved to #1027 #1029 )

![IMG_5183](https://user-images.githubusercontent.com/1294206/58275991-9c28d980-7d96-11e9-8b04-c1ecefab8e1e.PNG)

![IMG_5189](https://user-images.githubusercontent.com/1294206/58276987-080c4180-7d99-11e9-880a-0391c71fbda5.PNG)

![IMG_5190](https://user-images.githubusercontent.com/1294206/58276869-ce3b3b00-7d98-11e9-89cf-0bfca38e530a.PNG)

**Comment by TheoChevalier** [comment]
Morphing this bug to include additional missing strings:

![IMG_5189](https://user-images.githubusercontent.com/1294206/58276987-080c4180-7d99-11e9-880a-0391c71fbda5.PNG)

![IMG_5190](https://user-images.githubusercontent.com/1294206/58276869-ce3b3b00-7d98-11e9-89cf-0bfca38e530a.PNG)

**Comment by devinreams** [comment]
Thanks for the report @TheoChevalier. We'll look at this shortly...

**Comment by devinreams** [comment]
>“Sync between devices with secure 256-bits encryption” → Exposed, but not used

@sashei I can't tell why this one may not be connecting up:

>“Sync between devices with secure 256-bits encryption” → Exposed, but not used

Anything obvious jump out at you? I'll look more tomorrow

**Comment by sashei** [comment]
@devinreams we are doing manual interpolation to put the link in for `256-bit encryption`. Looking at some languages, we expect the storyboard text to match exactly a _different_ piece of text that's localized as `Constant.string.onboardingSecurityPostfix`. The string formatting is definitely failing because the strings (the one in the storyboard + the one in the generic `Localizable.strings`) don't line up. I think we need to tweak how we are getting that string interpolated + localized to work (although I'm not sure why it would fall back to English when the string formatting fails??).

All that to say, we need a bigger string change, which I think would be best addressed after l10n is shipped. For a quick fix, we could remove the string formatting (lines `60-77`) in the `OnboardingConfirmationVIew` and ship the initial localized version without the explainer encryption link.

**Comment by sashei** [comment]
I've filed a new ticket for the encryption text issue: #1061
