### ISSUE TITLE
Can't autofill on Odysee app

### ISSUE THREAD

**Issue by Mennaruuk** [mozilla-lockwise/lockwise-ios#1248]
## Steps to reproduce
1. Launch Odysee
2. Click Log In
3. See if an autofill option is offered
### Expected behavior
An option to autofill using existing credentials should appear.
### Actual behavior
No option exists to autofill using existing credentials.
### Device & build information
* Device: iPhone X
* Build version: 1.8.0

**Comment by cazeip** [comment]
I think this **doesn't** really **depend on Lockwise**. If the option doesn't appear, it's because **iOS didn't detect that it's a login** and **doesn't show** the option of auto-completing using Lockwise.

If you also use **another Password Manager**, and the **Autofill option doesn't appear**, it will prove that it **doesn't depend on Lockwise**.

**Contact the developers of Odysee** app to tell them to **change the structure** of the **Login Window** to make it detectable.
