### ISSUE TITLE
The user is taken back to the "Welcome screen" when force quitting the app while in the "confirmation" state

### ISSUE THREAD

**Issue by csuciu** [mozilla-lockwise/lockwise-ios#663]
iPhone X (11.4.1)
v1.2 (2018)

1. Sign in with an account that needs confirmation.
2. Do not confirm the email.
3. While in the confirmation state, force quit the app.
4. Re-open the app.

Expected:  App re-opens to an empty "confirmation" state.

Actual: The user is taken back to the "Welcome screen"

**Comment by devinreams** [comment]
Ah interesting, I had hoped (but not confirmed or tested) this would drop the user into the empty list view with the "Confirmation" blurb displayed.

**Comment by linuxwolf** [comment]
With OAuth, I think this might be expected behavior.  From the app's perspective, the user hasn't finished signing in.

May need to explore how to remember we're in the middle of this process, and attempt to automatically restart it.  The user will need to re-enter their password, but the FxA server shouldn't have to reconfim the account.

**Comment by sashei** [comment]
Can confirm that we don't have the `Confirmation` state anymore on the Lockbox side; this all happens via FxA. IIRC they are working on a way to maintain that state in the WebView so that you are dropped back into the "Confirm" page when going back to FxA from `Get Started`. However we would have to build in more functionality to maintain that state locally.

**Comment by sandysage** [comment]
Unfortunately there really isn't anything we can do about this state. Closing as wont-fix.
