### ISSUE TITLE
Only Firefox credentials are  displayed in the AutoFill list in Firefox iOS

### ISSUE THREAD

**Issue by SimonBasca** [mozilla-lockwise/lockwise-ios#705]
Build: 15e1604
Device: iPhone 7
iOS: 12b6

Pre - conditions:

- Clean install
- Log in to Lockbox
- Enable Autofill for Lockbox from iOS settings

Steps to reproduce:
1. In Firefox for iOS go to facebook.com
2. Tap on the username field
3. Tap on the Autofill icon

Actual results: 
- Six credentials are randomly displayed in the list. 

Expected results:
- Not sure what the expected behavior should be but the 6 credentials should be displayed by recent use or by alphabetical order.

@devinreams can you shed some light on what should be the expected behavior here? 

![screen shot 2018-09-12 at 5 27 43 pm](https://user-images.githubusercontent.com/32130829/45433092-1bb4c380-b6b4-11e8-9713-ab8f1efa72c4.png)

**Comment by devinreams** [comment]
Ooooooh I believe this is because the Firefox iOS app (browser) is registered to the firefox.com domain. So the AutoFill looks at any forms in the app and says "these forms are for firefox.com" not the actual website. I will surface this theory to the mobile team.

@SimonBasca if you use Safari it should work as expected and provide you with the domains of the website you're looking at. And with other apps (Twitter, Facebook) it should provide you with the credentials for the associated app (twitter.com, facebook.com). Does that help make sense?

**Comment by garvankeeley** [comment]
Firefox iOS bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1466751

**Comment by devinreams** [comment]
And another bug for what may be something related to surfacing the domain the webpage is on to the QuickType Bar: https://bugzilla.mozilla.org/show_bug.cgi?id=1490707

**Comment by sashei** [comment]
We are unable to do much to resolve this issue given the iOS system limitations; closing until we can find a way to interact more directly to support Firefox.

**Comment by 1096859788As** [comment]
Y
