### ISSUE TITLE
Update screenshots for new iOS devices

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-ios#708]
https://developer.apple.com/ios/submit/

>Upload screenshots to App Store Connect. Upload screenshots for the new iPhone XS Max, with a resolution of 1242 by 2688 pixels for portrait orientation and 2688 by 1242 pixels for landscape orientation. These assets will be automatically resized for iPhone X and later. Starting March 2019, all app submissions for iPhone, including universal apps, will require iPhone XS Max screenshots.

>    Upload screenshots as they are, with no modifications. The rounded corners will be automatically applied after upload.
>    If you add text descriptions to your screenshots, keep text away from the corners to avoid cropping.
>    Leave the home indicator in the screenshot, if it’s visible.
>    Avoid placing screenshots within a hardware device image.

We have until March 2019 to update to iPhone XS.

**Comment by devinreams** [comment]
@changecourse we now _have to_ provide 6.5" display screenshots and iPad Pro 3rd gen 12.9" screenshots in order to submit an app update:

https://help.apple.com/app-store-connect/#/devd274dd925

**Comment by changecourse** [comment]
If I'm reading everything correctly, we need to sets of iPhone screenshots and one set of iPad screenshots (since both 2nd and 3rd generations have the same resolution specs)

@devinreams can you look over the following folder and let me know if this satisfies the request? 

https://drive.google.com/open?id=1dRWqAdiSJAWCoR6b7gy1eBBiD_sk-Q6l&authuser=rgaddis@mozilla.com&usp=drive_fs

**Comment by devinreams** [comment]
We have proper and updated screenshots both for 1.5.0 and 1.6.0. Thanks @changecourse!
